<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>

    <OutputType>Exe</OutputType>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>2.0.0.1</Version>
    <IsPackable>false</IsPackable>
    <AssemblyTitle>QuickZvecTest</AssemblyTitle>
    <AssemblyCompany>MPCoreDeveloper</AssemblyCompany>
    <AssemblyCopyright>Copyright (c) 2026 MPCoreDeveloper and GitHub Copilot. All rights reserved.</AssemblyCopyright>
    <AssemblyVersion>2.0.0.1</AssemblyVersion>
    <FileVersion>2.0.0.1</FileVersion>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\SharpCoreDB\SharpCoreDB.csproj" />
    <ProjectReference Include="..\..\..\src\SharpCoreDB.VectorSearch\SharpCoreDB.VectorSearch.csproj" />
  </ItemGroup>

  <ItemGroup>
    
  </ItemGroup>

</Project>

