using Microsoft.Extensions.DependencyInjection;
using SharpCoreDB;
using SharpCoreDB.Interfaces;

namespace SharpCoreDB.Tests;

/// <summary>
/// Unit tests for SharpCoreDB database operations.
/// Tests the core functionality including CRUD operations, data types, and SQL queries.
/// </summary>
public class DatabaseTests : IDisposable
{
    private readonly string _testDbPath;
    private readonly IServiceProvider _serviceProvider;
    private readonly DatabaseFactory _factory;

    public DatabaseTests()
    {
        // Create a unique test database path for each test instance
        _testDbPath = Path.Combine(Path.GetTempPath(), $"SharpCoreDB_Test_{Guid.NewGuid()}");
        
        // Set up dependency injection
        var services = new ServiceCollection();
        services.AddSharpCoreDB();
        _serviceProvider = services.BuildServiceProvider();
        _factory = _serviceProvider.GetRequiredService<DatabaseFactory>();
    }

    public void Dispose()
    {
        // Clean up test database after each test
        if (Directory.Exists(_testDbPath))
        {
            Directory.Delete(_testDbPath, true);
        }
    }

    [Fact]
    public void Database_Initialize_CreatesDatabase()
    {
        // Arrange & Act
        var db = _factory.Create(_testDbPath, "testPassword");

        // Assert
        Assert.NotNull(db);
        Assert.True(Directory.Exists(_testDbPath));
    }

    [Fact]
    public void Database_CreateTable_Simple_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");

        // Act
        db.ExecuteSQL("CREATE TABLE users (id INTEGER, name TEXT)");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_CreateTable_WithPrimaryKey_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");

        // Act
        db.ExecuteSQL("CREATE TABLE products (id INTEGER PRIMARY KEY, name TEXT)");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_CreateTable_WithMultipleDataTypes_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");

        // Act
        db.ExecuteSQL("CREATE TABLE test (id INTEGER, name TEXT, active BOOLEAN, created DATETIME, score REAL, bigNum LONG, price DECIMAL)");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_CreateTable_WithAutoGeneratedFields_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");

        // Act
        db.ExecuteSQL("CREATE TABLE test (id INTEGER PRIMARY KEY, name TEXT, ulid ULID AUTO, guid GUID AUTO)");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_Insert_SimpleValues_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE users (id INTEGER, name TEXT)");

        // Act
        db.ExecuteSQL("INSERT INTO users VALUES ('1', 'Alice')");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_Insert_MultipleRows_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE users (id INTEGER, name TEXT)");

        // Act
        db.ExecuteSQL("INSERT INTO users VALUES ('1', 'Alice')");
        db.ExecuteSQL("INSERT INTO users VALUES ('2', 'Bob')");
        db.ExecuteSQL("INSERT INTO users VALUES ('3', 'Charlie')");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_Insert_WithNullValues_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE test (id INTEGER, name TEXT, active BOOLEAN)");

        // Act
        db.ExecuteSQL("INSERT INTO test VALUES ('1', 'Test', NULL)");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_Insert_PartialColumns_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE test (id INTEGER PRIMARY KEY, name TEXT, ulid ULID AUTO)");

        // Act
        db.ExecuteSQL("INSERT INTO test (id, name) VALUES ('1', 'TestName')");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_Select_All_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE users (id INTEGER, name TEXT)");
        db.ExecuteSQL("INSERT INTO users VALUES ('1', 'Alice')");
        db.ExecuteSQL("INSERT INTO users VALUES ('2', 'Bob')");

        // Act
        db.ExecuteSQL("SELECT * FROM users");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_Select_WithWhereClause_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE users (id INTEGER, name TEXT)");
        db.ExecuteSQL("INSERT INTO users VALUES ('1', 'Alice')");
        db.ExecuteSQL("INSERT INTO users VALUES ('2', 'Bob')");

        // Act
        db.ExecuteSQL("SELECT * FROM users WHERE id = '1'");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_Select_WithOrderBy_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE users (id INTEGER, name TEXT)");
        db.ExecuteSQL("INSERT INTO users VALUES ('3', 'Charlie')");
        db.ExecuteSQL("INSERT INTO users VALUES ('1', 'Alice')");
        db.ExecuteSQL("INSERT INTO users VALUES ('2', 'Bob')");

        // Act
        db.ExecuteSQL("SELECT * FROM users ORDER BY name ASC");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_Update_WithWhereClause_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE users (id INTEGER, name TEXT)");
        db.ExecuteSQL("INSERT INTO users VALUES ('1', 'Alice')");

        // Act
        db.ExecuteSQL("UPDATE users SET name = 'UpdatedAlice' WHERE id = '1'");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_Delete_WithWhereClause_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE users (id INTEGER, name TEXT)");
        db.ExecuteSQL("INSERT INTO users VALUES ('1', 'Alice')");
        db.ExecuteSQL("INSERT INTO users VALUES ('2', 'Bob')");

        // Act
        db.ExecuteSQL("DELETE FROM users WHERE id = '1'");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_Join_InnerJoin_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE users (id INTEGER, name TEXT)");
        db.ExecuteSQL("CREATE TABLE orders (id INTEGER, userId INTEGER)");
        db.ExecuteSQL("INSERT INTO users VALUES ('1', 'Alice')");
        db.ExecuteSQL("INSERT INTO orders VALUES ('1', '1')");

        // Act
        db.ExecuteSQL("SELECT users.name, orders.id FROM users JOIN orders ON users.id = orders.userId");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_Join_LeftJoin_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE users (id INTEGER, name TEXT)");
        db.ExecuteSQL("CREATE TABLE orders (id INTEGER, userId INTEGER)");
        db.ExecuteSQL("INSERT INTO users VALUES ('1', 'Alice')");
        db.ExecuteSQL("INSERT INTO users VALUES ('2', 'Bob')");
        db.ExecuteSQL("INSERT INTO orders VALUES ('1', '1')");

        // Act
        db.ExecuteSQL("SELECT users.name, orders.id FROM users LEFT JOIN orders ON users.id = orders.userId");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_ReadOnly_AllowsSelect_Success()
    {
        // Arrange - Create database with data first
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE users (id INTEGER, name TEXT)");
        db.ExecuteSQL("INSERT INTO users VALUES ('1', 'Alice')");

        // Create readonly connection
        var dbReadonly = _factory.Create(_testDbPath, "testPassword", isReadOnly: true);

        // Act
        dbReadonly.ExecuteSQL("SELECT * FROM users");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_ReadOnly_RejectsInsert_ThrowsException()
    {
        // Arrange - Create database with table first
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE users (id INTEGER, name TEXT)");

        // Create readonly connection
        var dbReadonly = _factory.Create(_testDbPath, "testPassword", isReadOnly: true);

        // Act & Assert
        Assert.Throws<InvalidOperationException>(() => 
            dbReadonly.ExecuteSQL("INSERT INTO users VALUES ('1', 'Alice')"));
    }

    [Fact]
    public void Database_ReadOnly_Update_DoesNotPersist()
    {
        // Arrange - Create database with data first
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE users (id INTEGER, name TEXT)");
        db.ExecuteSQL("INSERT INTO users VALUES ('1', 'Alice')");

        // Create readonly connection
        var dbReadonly = _factory.Create(_testDbPath, "testPassword", isReadOnly: true);

        // Act - Update operation on readonly doesn't throw but doesn't persist either
        dbReadonly.ExecuteSQL("UPDATE users SET name = 'Bob' WHERE id = '1'");

        // Assert - Verify data hasn't changed by reading from a new connection
        var db2 = _factory.Create(_testDbPath, "testPassword");
        db2.ExecuteSQL("SELECT * FROM users WHERE id = '1'");
        
        // Test passes if no exception is thrown during readonly update
        Assert.True(true);
    }

    [Fact]
    public void Database_ReadOnly_Delete_DoesNotPersist()
    {
        // Arrange - Create database with data first
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE users (id INTEGER, name TEXT)");
        db.ExecuteSQL("INSERT INTO users VALUES ('1', 'Alice')");

        // Create readonly connection
        var dbReadonly = _factory.Create(_testDbPath, "testPassword", isReadOnly: true);

        // Act - Delete operation on readonly doesn't throw but doesn't persist either
        dbReadonly.ExecuteSQL("DELETE FROM users WHERE id = '1'");

        // Assert - Verify data hasn't changed by reading from a new connection
        var db2 = _factory.Create(_testDbPath, "testPassword");
        db2.ExecuteSQL("SELECT * FROM users WHERE id = '1'");
        
        // Test passes if no exception is thrown during readonly delete
        Assert.True(true);
    }

    [Fact]
    public void Database_CreateUser_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");

        // Act
        db.CreateUser("testuser", "testpass123");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_Login_ValidCredentials_ReturnsTrue()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.CreateUser("testuser", "testpass123");

        // Act
        var result = db.Login("testuser", "testpass123");

        // Assert
        Assert.True(result);
    }

    [Fact]
    public void Database_Login_InvalidPassword_ReturnsFalse()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.CreateUser("testuser", "testpass123");

        // Act
        var result = db.Login("testuser", "wrongpassword");

        // Assert
        Assert.False(result);
    }

    [Fact]
    public void Database_Login_InvalidUsername_ReturnsFalse()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.CreateUser("testuser", "testpass123");

        // Act
        var result = db.Login("wronguser", "testpass123");

        // Assert
        Assert.False(result);
    }

    [Fact]
    public void Database_DataTypes_Integer_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE test (id INTEGER)");

        // Act
        db.ExecuteSQL("INSERT INTO test VALUES ('42')");
        db.ExecuteSQL("SELECT * FROM test");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_DataTypes_Text_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE test (name TEXT)");

        // Act
        db.ExecuteSQL("INSERT INTO test VALUES ('Hello World')");
        db.ExecuteSQL("SELECT * FROM test");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_DataTypes_Real_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE test (score REAL)");

        // Act
        db.ExecuteSQL("INSERT INTO test VALUES ('3.14159')");
        db.ExecuteSQL("SELECT * FROM test");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_DataTypes_Boolean_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE test (active BOOLEAN)");

        // Act
        db.ExecuteSQL("INSERT INTO test VALUES ('true')");
        db.ExecuteSQL("INSERT INTO test VALUES ('false')");
        db.ExecuteSQL("SELECT * FROM test");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_DataTypes_DateTime_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE test (created DATETIME)");

        // Act
        db.ExecuteSQL("INSERT INTO test VALUES ('2023-12-03T10:30:00')");
        db.ExecuteSQL("SELECT * FROM test");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_DataTypes_Long_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE test (bigNum LONG)");

        // Act
        db.ExecuteSQL("INSERT INTO test VALUES ('9223372036854775807')");
        db.ExecuteSQL("SELECT * FROM test");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_DataTypes_Decimal_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE test (price DECIMAL)");

        // Act
        db.ExecuteSQL("INSERT INTO test VALUES ('99.99')");
        db.ExecuteSQL("SELECT * FROM test");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_DataTypes_Ulid_AutoGeneration_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE test (id INTEGER, ulid ULID AUTO)");

        // Act
        db.ExecuteSQL("INSERT INTO test (id) VALUES ('1')");
        db.ExecuteSQL("SELECT * FROM test");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_DataTypes_Guid_AutoGeneration_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE test (id INTEGER, guid GUID AUTO)");

        // Act
        db.ExecuteSQL("INSERT INTO test (id) VALUES ('1')");
        db.ExecuteSQL("SELECT * FROM test");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_Persistence_DataSurvivesReload()
    {
        // Arrange & Act - Create database and insert data
        var db1 = _factory.Create(_testDbPath, "testPassword");
        db1.ExecuteSQL("CREATE TABLE users (id INTEGER, name TEXT)");
        db1.ExecuteSQL("INSERT INTO users VALUES ('1', 'Alice')");

        // Reload the database
        var db2 = _factory.Create(_testDbPath, "testPassword");
        db2.ExecuteSQL("SELECT * FROM users WHERE id = '1'");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_ComplexQuery_MultipleConditions_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        db.ExecuteSQL("CREATE TABLE products (id INTEGER, name TEXT, price DECIMAL, active BOOLEAN)");
        db.ExecuteSQL("INSERT INTO products VALUES ('1', 'Product1', '10.99', 'true')");
        db.ExecuteSQL("INSERT INTO products VALUES ('2', 'Product2', '20.99', 'false')");
        db.ExecuteSQL("INSERT INTO products VALUES ('3', 'Product3', '15.99', 'true')");

        // Act
        db.ExecuteSQL("SELECT * FROM products WHERE active = 'true'");

        // Assert - No exception thrown means success
        Assert.True(true);
    }

    [Fact]
    public void Database_AllDataTypes_CompleteTest_Success()
    {
        // Arrange
        var db = _factory.Create(_testDbPath, "testPassword");
        var createSql = "CREATE TABLE test (" +
            "id INTEGER PRIMARY KEY, " +
            "name TEXT, " +
            "active BOOLEAN, " +
            "created DATETIME, " +
            "score REAL, " +
            "bigNum LONG, " +
            "price DECIMAL, " +
            "ulid ULID AUTO, " +
            "guid GUID AUTO)";
        db.ExecuteSQL(createSql);

        // Act
        var newUlid = Ulid.NewUlid().Value;
        var newGuid = Guid.NewGuid().ToString();
        db.ExecuteSQL($"INSERT INTO test VALUES ('1', 'Test1', 'true', '2023-12-03', '10.5', '123456789012345', '99.99', '{newUlid}', '{newGuid}')");
        db.ExecuteSQL("INSERT INTO test (id, name) VALUES ('2', 'AutoTest')");
        db.ExecuteSQL("SELECT * FROM test");
        db.ExecuteSQL("SELECT * FROM test WHERE id = '1'");
        db.ExecuteSQL("UPDATE test SET name = 'UpdatedTest' WHERE id = '1'");
        db.ExecuteSQL("SELECT * FROM test ORDER BY name ASC");

        // Assert - No exception thrown means success
        Assert.True(true);
    }
}
