<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <!-- Manual test demo, not a NuGet package -->
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    
  </ItemGroup>

</Project>
